In [1]:
print('hello world!')

hello world!


In [6]:
var = '{}, {}'.format(1, 1)
print(var * 2)

1, 11, 1


In [30]:
import numpy as np
a = np.ones((7,7), int)
b = np.ones((9,9), int)
for i in range(9):
    for j in range(9):
        b[i][j] = (i + 1) * (j + 1)

for i in range(3):
    for j in range(3):
        if not 0 in b[i:7+i, j:7+j]:
            

[[ 1  2  3  4  5  6  7]
 [ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]
 [ 7 14 21 28 35 42 49]]
[[ 2  3  4  5  6  7  8]
 [ 4  6  8 10 12 14 16]
 [ 6  9 12 15 18 21 24]
 [ 8 12 16 20 24 28 32]
 [10 15 20 25 30 35 40]
 [12 18 24 30 36 42 48]
 [14 21 28 35 42 49 56]]
[[ 3  4  5  6  7  8  9]
 [ 6  8 10 12 14 16 18]
 [ 9 12 15 18 21 24 27]
 [12 16 20 24 28 32 36]
 [15 20 25 30 35 40 45]
 [18 24 30 36 42 48 54]
 [21 28 35 42 49 56 63]]
[[ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]
 [ 7 14 21 28 35 42 49]
 [ 8 16 24 32 40 48 56]]
[[ 4  6  8 10 12 14 16]
 [ 6  9 12 15 18 21 24]
 [ 8 12 16 20 24 28 32]
 [10 15 20 25 30 35 40]
 [12 18 24 30 36 42 48]
 [14 21 28 35 42 49 56]
 [16 24 32 40 48 56 64]]
[[ 6  8 10 12 14 16 18]
 [ 9 12 15 18 21 24 27]
 [12 16 20 24 28 32 36]
 [15 20 25 30 35 40 45]
 [18 24 30 36 42 48 54]
 [21 28 35 42 49 56 63]
 [24 32 40 

In [3]:
import numpy as np
arr = np.array((1), int)
arr.shape

()

In [2]:
7 + (7 if False == 1 else 0)

7

In [208]:
# create pieces
matrix = np.zeros((9,9), int)
piece = {}
piece[3] = np.array(([1,1]))
piece[4] = np.array(([1,1], [0,1]))
piece[5] = np.array(([1,1], [0,1]))
piece[6] = np.array(([1,1,1]))
piece[7] = np.array(([1,1], [1,1]))
piece[8] = np.array(([1,1,1,1]))
piece[9] = np.array(([1,1,1], [1,0,0]))
piece[10] = np.array(([1,1,1], [1,0,0]))
piece[11] = np.array(([1,1,1], [0,1,0]))
piece[12] = np.array(([0,1,1], [1,1,0]))
piece[13] = np.array(([0,1,1], [1,1,0]))
piece[14] = np.array(([0,1,0], [1,1,1], [0,1,0]))
piece[15] = np.array(([1,0,1], [1,1,1]))
piece[16] = np.array(([1,1,1], [1,1,0]))
piece[17] = np.array(([1,1,1], [0,1,0], [0,1,0]))
piece[18] = np.array(([0,1,0,0], [1,1,1,1]))
piece[19] = np.array(([1,1,0,0], [0,1,1,1]))
piece[20] = np.array(([1,0,0], [1,1,0], [0,1,1]))
piece[21] = np.array(([1,0,0,0], [1,1,1,1]))
piece[22] = np.array(([0,1,1], [1,1,0], [0,1,1]))
piece[23] = np.array(([1,1,0,0], [1,1,1,1]))
piece[24] = np.array(([0,1,1,0], [1,1,1,1]))
piece[25] = np.array(([0,1,0,0], [1,1,1,1], [0,1,0,0]))
piece[26] = np.array(([0,0,1,0], [1,1,1,1], [0,1,0,0]))
piece[27] = np.array(([1,1,0], [1,1,0], [0,1,1]))
piece[28] = np.array(([1,0,0,1], [1,1,1,1]))
piece[29] = np.array(([1,0,0,0], [1,1,1,1], [0,0,0,1]))
piece[30] = np.array(([0,0,0,1], [1,1,1,1], [0,0,0,1]))
piece[31] = np.array(([0,1,1,1], [1,1,1,0]))
piece[32] = np.array(([0,0,1,0,0], [1,1,1,1,1], [0,0,1,0,0]))
piece[33] = np.array(([1,1,1], [0,1,0], [1,1,1]))
piece[34] = np.array(([0,1,1,0], [1,1,1,1], [0,1,1,0]))

In [27]:
# add_patch_to_matrix code
def add_patch_to_matrix(matrix, patch, coor:tuple):
        temp_matrix = matrix.copy()

        temp_patch = patch

        if len(temp_patch.shape) == 2:
            temp_matrix[coor[0]:coor[0] + temp_patch.shape[0], coor[1]:coor[1] + temp_patch.shape[1]] += temp_patch  # use array slicing
        else:
            temp_matrix[coor[0]:coor[0] + 1, coor[1]:coor[1] + len(temp_patch)][0] += temp_patch  # use array slicing
        return temp_matrix

In [44]:
def find_variations(patch):
    variations = [patch]
    patch = np.rot90(patch, k = 1)
    variations.append(patch)
    patch = np.rot90(patch, k = 1)
    variations.append(patch)
    patch = np.rot90(patch, k = 1)
    variations.append(patch)
    patch = np.flipud(patch)
    variations.append(patch)
    patch = np.rot90(patch, k = 1)
    variations.append(patch)
    patch = np.rot90(patch, k = 1)
    variations.append(patch)
    patch = np.rot90(patch, k = 1)
    variations.append(patch)

    temp = []
    temp_nums = []
    for i, variation in enumerate(variations):
        if variation.tolist() in temp:
            temp_nums.append(i)
        temp.append(variation.tolist())

    temp_nums.reverse()
    for i in temp_nums:
        del variations[i]

    shapes = []
    for variation in variations:
        shape = variation.shape
        if len(shape) == 1:
            shape = (shape[0], 1)
        shapes.append(shape)

    return zip(variations, shapes)


In [47]:
def possible_coors(shape:tuple):
    coors = []
    for i in range(10 - shape[0]):
        for j in range(10 - shape[1]):
            coors.append((i, j))

    return coors

In [209]:
def score(matrix, edge_bonus:float = 1.0, neighbor_bonus:float = 2.0, blank_neighbor_penalty:float = 0.5, \
    hard_to_fill_penalty:float = 5.0, less_hard_to_fill_penalty:float = 1.0):

    if 2 in matrix:
        raise Exception('cannot have a 2 in the matrix')
        # raise Error

    score = 0

    left_edge, right_edge, top_edge, bottom_edge = False, False, False, False
    for i in range(9):
        for j in range(9):
            
            sides_blocked = 0
            
            if matrix[i, j] == 1:
                if i == 0:
                    score += edge_bonus
                    left_edge = True
                if i == 8:
                    score += edge_bonus
                    right_edge = True
                if j == 0:
                    score += edge_bonus
                    top_edge = True
                if j == 8:
                    score += edge_bonus
                    bottom_edge = True
                if not right_edge:
                    if matrix[i+1, j] == 1:
                        score += neighbor_bonus
                    else:
                        score -= blank_neighbor_penalty
                if not left_edge:
                    if matrix[i-1, j] == 1:
                        score += neighbor_bonus
                    else:
                        score -= blank_neighbor_penalty
                if not top_edge:
                    if matrix[i, j-1] == 1:
                        score += neighbor_bonus
                    else:
                        score -= blank_neighbor_penalty
                if not bottom_edge:
                    if matrix[i, j+1] == 1:
                        score += neighbor_bonus
                    else:
                        score -= blank_neighbor_penalty
            if matrix[i, j] == 0:
                if i == 0:
                    left_edge = True
                if i == 8:
                    right_edge = True
                if j == 0:
                    top_edge = True
                if j == 8:
                    bottom_edge = True
                if not i == 8:
                    if matrix[i+1, j] == 1:
                        sides_blocked += 1
                else:
                    sides_blocked += 1
                
                if not i == 0:
                    if matrix[i-1, j] == 1:
                        sides_blocked += 1
                else: 
                    sides_blocked += 1
            
                if not j == 8:
                    if matrix[i, j+1] == 1:
                        sides_blocked += 1
                else:
                    sides_blocked += 1
                
                if not j == 0:
                    if matrix[i, j-1] == 1:
                        sides_blocked += 1
                else: 
                    sides_blocked += 1

                if sides_blocked == 4:
                    score -= hard_to_fill_penalty

                if sides_blocked == 3:
                    score -= less_hard_to_fill_penalty
                    
            left_edge, right_edge, top_edge, bottom_edge = False, False, False, False
    
    
    return score
                    
matrix = np.ones((9,9), int)
print(score(matrix, 1.0, 2.0, 0.5))
matrix[3,4] = 0
print(score(matrix, 1.0, 2.0, 0.5, hard_to_fill_penalty=100.0))

612.0
494.0


In [211]:
matrix = np.zeros((9,9), int)

In [219]:
from random import randrange
def find_best_placement(matrix, piece_num):
    results = []

    patch = piece[piece_num]
    if len(patch.shape) == 1:
        patch = patch[np.newaxis]

    for variation, shape in find_variations(piece[piece_num]):
        for coor in possible_coors(shape):
            try:
                temp_score = score(add_patch_to_matrix(matrix, variation, coor), hard_to_fill_penalty=100, less_hard_to_fill_penalty=1.0)
                results.append((variation, coor, temp_score))
            except:
                pass

    highest_score = -9999999
    important_variation = -9999999
    important_coor = -9999999
    for variation, coor, temp_score in results:
        if temp_score > highest_score:
            highest_score = temp_score
            important_variation = variation
            important_coor = coor
    try:
        return add_patch_to_matrix(matrix, important_variation, important_coor)
    except Exception as e:
        print('no solution')
        print(f'patch with no fit:\n {piece[piece_num]}')
        print('matrix it wont fit on:')
        return matrix

piece_num = randrange(3, 35)
print(piece_num)
matrix = find_best_placement(matrix, piece_num)
print(matrix)


3


ValueError: Axes must be different.